#!/usr/bin/env Rscript
# Translate a Capr-style concept-set YAML into Capr R code AND ATLAS-compatible JSON.
#
# Why Capr (OHDSI/Capr v2): canonical R API for OHDSI cohort definitions; concept
# sets can be built without a database connection (only OMOP concept_ids needed).
# Renders to the same Circe-be JSON ATLAS produces, so concept sets are portable
# between Capr code and ATLAS UI.
#
# Usage:
#   Rscript concept_set_to_capr.R \
#     --in analysis/cohort/concept-sets/T2DM.yaml \
#     --out-r analysis/cohort/concept-sets/T2DM.R \
#     --out-json analysis/cohort/concept-sets/T2DM.json
#
# Required: install.packages("Capr") OR remotes::install_github("OHDSI/Capr")
#           install.packages("yaml")

suppressPackageStartupMessages({
  if (!requireNamespace("yaml", quietly = TRUE)) {
    stop("install yaml: install.packages('yaml')")
  }
  if (!requireNamespace("Capr", quietly = TRUE)) {
    stop("install Capr: install.packages('Capr') or remotes::install_github('OHDSI/Capr')")
  }
  library(yaml)
  library(Capr)
})

parse_args <- function(args) {
  out <- list()
  i <- 1
  while (i <= length(args)) {
    key <- sub("^--", "", args[i])
    out[[key]] <- args[i + 1]
    i <- i + 2
  }
  out
}

args <- parse_args(commandArgs(trailingOnly = TRUE))
stopifnot(!is.null(args$`in`), !is.null(args$`out-r`), !is.null(args$`out-json`))

spec   <- yaml::read_yaml(args$`in`)
cs_def <- spec$concept_set
stopifnot(!is.null(cs_def), !is.null(cs_def$primary_concepts))

# Build Capr cs() call programmatically.
# cs(<concept_ids>, exclude(<ids>), descendants(<ids>), name = "...")
primary_ids   <- vapply(cs_def$primary_concepts, function(x) as.integer(x$concept_id), integer(1))
include_desc  <- isTRUE(cs_def$primary_concepts[[1]]$include_descendants)

excl_ids <- if (!is.null(cs_def$excluded_concepts)) {
  vapply(cs_def$excluded_concepts, function(x) as.integer(x$concept_id), integer(1))
} else integer(0)

cs_args <- list()
if (include_desc) {
  cs_args <- c(cs_args, list(do.call(descendants, as.list(primary_ids))))
} else {
  cs_args <- c(cs_args, as.list(primary_ids))
}
if (length(excl_ids) > 0) {
  cs_args <- c(cs_args, list(do.call(exclude, as.list(excl_ids))))
}
cs_args$name <- cs_def$name

concept_set <- do.call(Capr::cs, cs_args)

# Write Capr R code mirror so the YAML stays the source of truth but R can re-derive.
r_code <- c(
  "# Auto-generated from concept-set YAML by concept_set_to_capr.R",
  "# Vocabulary version pinning lives in the YAML; do not edit this file directly.",
  "library(Capr)",
  "",
  sprintf('# %s (%s, vocab %s)',
          cs_def$name,
          cs_def$vocabulary %||% "OMOP",
          cs_def$vocabulary_version %||% "UNPINNED -- FIX YAML"),
  "",
  paste0(cs_def$name, " <- ", deparse(match.call(Capr::cs, sys.call(0)))[1])
)
writeLines(r_code, args$`out-r`)

# Write the ATLAS-compatible JSON.
Capr::writeConceptSet(concept_set, args$`out-json`)

cat(sprintf("__CE_COHORT_CAPR__ name=%s n_primary=%d include_descendants=%s n_excluded=%d r=%s json=%s\n",
            cs_def$name, length(primary_ids), include_desc, length(excl_ids),
            args$`out-r`, args$`out-json`))
